config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'polizas#index', as: 'polizas_index'
resources :polizas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poliza.rb
class Poliza < ApplicationRecord
  validates :poliza_a_migrar, length: { is: 7, wrong_length: ": la póliza esta conformada por 7 dígitos numéricos." }
  validates :poliza_a_migrar, uniqueness: { message: ": póliza registrada previamente."}
  validates :poliza_a_migrar, presence: { message: ": la póliza no puede estar en blanco."}
  validates :poliza_a_migrar, format: { with: /\A3[\d{6}]+\z/,
    message: ": la póliza debe comenzar por 3 y todos los dígitos son numéricos." }
  validate :expiration_date_cannot_be_in_the_past

  def expiration_date_cannot_be_in_the_past
    if fecha_migracion < Date.today
      errors.add(:fecha_migracion, ": la fecha a migrar no puede ser anterior a hoy.")
    end
  end   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/polizas_controller.rb
class PolizasController < ApplicationController
  before_action :set_poliza, only: [:show, :edit, :update, :destroy]
  before_action :ip_address


  # GET /polizas
  # GET /polizas.json
  def index
    @polizas = Poliza.all
  end

  # GET /polizas/1
  # GET /polizas/1.json
  def show
  end

  # GET /polizas/new
  def new
    @poliza = Poliza.new
  end

  # GET /polizas/1/edit
  def edit
  end

  # POST /polizas
  # POST /polizas.json
  def create
    @poliza = Poliza.new(poliza_params)

    respond_to do |format|
      if @poliza.save
        format.html { redirect_to @poliza, notice: 'Poliza was successfully created.' }
        format.json { render :show, status: :created, location: @poliza }
      else
        format.html { render :new }
        format.json { render json: @poliza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polizas/1
  # PATCH/PUT /polizas/1.json
  def update
    respond_to do |format|
      if @poliza.update(poliza_params)
        format.html { redirect_to @poliza, notice: 'Poliza was successfully updated.' }
        format.json { render :show, status: :ok, location: @poliza }
      else
        format.html { render :edit }
        format.json { render json: @poliza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polizas/1
  # DELETE /polizas/1.json
  def destroy
    @poliza.destroy
    respond_to do |format|
      format.html { redirect_to polizas_url, notice: 'Poliza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected
 
 def ip_address
    require 'socket' 
    ip=Socket.ip_address_list.detect{|intf| intf.ipv4_private?} 
    @ip_address =  request.env['REMOTE_ADDR']
    @fecha =  Time.now
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poliza
      @poliza = Poliza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poliza_params
      params.require(:poliza).permit(:poliza_a_migrar, :prima, :fecha_migracion, :observacion, :ip)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polizas_helper.rb
module PolizasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Migracion</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/polizas/_form.html.erb
<%= form_with(model: poliza, local: true) do |form| %>
  <% if poliza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poliza.errors.count, "error") %> prohibited this poliza from being saved:</h2>

      <ul>
      <% poliza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :poliza_a_migrar %>
    <%= form.text_field :poliza_a_migrar %>
  </div>

  <div class="field">
    <%= form.label :prima %>

    <%= form.select(:prima) do %>
      <% [['Prima Mensual: 613.89 Bs.', 62],['Prima Mensual: 245.56 Bs.', 60]].each do |c| -%>
        <%= content_tag(:option, c.first, value: c.last) %>
      <% end %>
  <% end %>


  </div>

  <div class="field">
    <%= form.label :fecha_migracion %>
    <%= form.date_select :fecha_migracion %>
  </div>

  <div class="field">
    <%= form.label :observacion %>
    <%= form.text_field :observacion %>
  </div>

  <div class="field">
    <%= form.hidden_field :ip, :value => @ip_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/polizas/edit.html.erb
<h1>Editing Poliza</h1>

<%= render 'form', poliza: @poliza %>

<%= link_to 'Show', @poliza %> |
<%= link_to 'Back', polizas_path %>

app/views/polizas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Polizas</h1>
<h2>IP: <%= @ip_address %> <%= @fecha.strftime("at %d-%m-%Y  %T") %></h2>
<%= link_to 'New Poliza', new_poliza_path %>
<br><br>

<table>
  <thead>
    <tr>
      <th>Cedula Tomador</th>
      <th>Poliza a migrar</th>
      <th>Cedula Asegurado</th>
      <th>Prima</th>
      <th>Fecha migracion</th>
      <th>Observacion</th>
      <th>Ip</th>
      <th>Conciliacion</th>
      <th>Fecha de Conciliacion</th>
      <th>Fecha de Nacimiento</th>
      <th>Excepción</td>
      <th>Anulada</th>
      <th>Fecha de Anulacion</th>
      <th>Migrada</th>
      <th>Poliza Migrada</th>
      <th>Fecha de Nueva Poliza</th>
      <th>Observacion migracion</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
  <% cache @polizas do %>
    <% @polizas.each do |poliza| %>
      <% cache poliza do %>	
      <tr>
        <td><%= poliza.CI_Tomador %></td>
        <td><%= poliza.poliza_a_migrar %></td>
        <td><%= poliza.CI_Asegurado %></td>
        <td><%= poliza.prima %></td>
        <td><%= poliza.fecha_migracion %></td>
        <td><%= truncate(poliza.observacion, length:10) %></td>
        <td><%= poliza.ip %></td>
        <td><%= poliza.conciliacion %></td>
        <td><%= poliza.fecha_conciliacion %></td>
        <td><%= poliza.fecha_nacimiento %></td>
        <td><%= poliza.excepcion %></td>
        <td><%= poliza.anulada %></td>
        <td><%= poliza.fecha_anulada %></td>
        <td><%= poliza.migrada %></td>
        <td><%= poliza.poliza_migrada %></td>
        <td><%= poliza.poliza_migrada_fecha %></td>
        <td><%= truncate(poliza.observacion_migracion, length:10) %></td>
        <td><%= link_to 'Show', poliza %></td>
        <td><%= link_to 'Edit', edit_poliza_path(poliza) %></td>
        
      </tr>
      <% end %>
    <% end %>
  <% end %>  
</tbody>
</table>

app/views/polizas/new.html.erb
<h1>New Poliza</h1>

<%= render 'form', poliza: @poliza %>

<%= link_to 'Back', polizas_path %>

app/views/polizas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Poliza a migrar:</strong>
  <%= @poliza.poliza_a_migrar %>
</p>

<p>
  <strong>Prima:</strong>
  <%= @poliza.prima %>
</p>

<p>
  <strong>Fecha migracion:</strong>
  <%= @poliza.fecha_migracion %>
</p>

<p>
  <strong>Observacion:</strong>
  <%= @poliza.observacion %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @poliza.ip %>
</p>

<%= link_to 'Edit', edit_poliza_path(@poliza) %> |
<%= link_to 'Back', polizas_path %>